### ISSUE TITLE
What should be included in the curriculum?

### ISSUE THREAD

**Issue by MylesBorins** [TheAlphaNerd/a11y-school#1]
- Intro to a11y
  - what is a11y
  - what is aria
  - what is a screen reader
  - alternative forms of user input
- How to use a screen reader
- Making a non accesible page accessible
- Testing accessibility
- Contrast for the visually impaired
- What and how to manage tab focus
- UI / UX that is easily understood by those with cognitive impairments
- Many more

**Comment by jkup** [comment]
These look great so far! I'd imagine it would be covered in "Testing Accessibility" but it would be great to talk about all the great free tools you can use to assess your website.

**Comment by giuseppeg** [comment]
you may want to add a lil section to highlight the benefits of writing semantic markup

**Comment by jkup** [comment]
+1 for that, in general is would be nice to highlight that a win for a11y is a win for everyone. Making accessibly websites means that keyboard-only power users, people on old browsers and search engines all love your site more!
